pluginManagement {
    includeBuild('../..')
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        id('name.jurgenei.gradle.ooxml') version '0.1.10'
    }

    def ooxmlBuild = file('../../../gradle-ooxml-plugin')
    if (ooxmlBuild.exists()) {
        includeBuild('../../../gradle-ooxml-plugin')
    }
}

rootProject.name = 'schematron-bootstrap-ooxml'
