/* (C)2026 */
package name.jurgenei.gradle.xml;

import java.io.File;
import javax.inject.Inject;

/**
 * Executes SHACL-driven SEL extraction.
 *
 * <p>This task reuses SEL runtime extraction behavior from {@link SchematronSelExtractTask}.
 * Typical flow compiles SHACL into grouped SEL stylesheet via {@link ShaclSelCompileTask},
 * then runs extraction using that precompiled style.</p>
 */
public abstract class ShaclSelExtractTask extends SchematronSelExtractTask {
    /**
     * Creates task instance.
     */
    @Inject
    public ShaclSelExtractTask() {
        super();
    }

    /**
     * Sets generated Schematron bridge schema path.
     *
     * <p>Unlike base Schematron task variant, existence is not checked at configuration time
     * because schema is typically generated by an upstream compile task.</p>
     *
     * @param path file notation accepted by {@code Project.file}.
     */
    @Override
    public void schema(Object path) {
        File file = getProject().file(path);
        getSchema().set(file);
    }
}
