name: checkstyle
on:
  push:
    branches: ["main", "release/**"]
  pull_request:
    branches: ["main", "release/**"]
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dbelyaev/action-checkstyle@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}